[workspace]
members = [
    "unplug",
    "unplug-cli",
    "unplug-data",
    "unplug-datagen",
    "unplug-proc",
    "unplug-test",
]
default-members = [
    "unplug",
    "unplug-cli",
    "unplug-data",
    "unplug-test",
]

[profile.release]
codegen-units = 1
debug = true
lto = "thin"
panic = "abort"