[package]
name = "unplug-cli"
version = "0.2.0"
authors = ["Derpky"]
edition = "2018"
default-run = "unplug"

[[bin]]
name = "unplug"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
byteorder = "1"
lazy_static = "1.4.0"
log = { version = "0.4", features = ["release_max_level_debug"] }
quick-xml = "0.22"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.10"
structopt = "0.3"
tempfile = "3"
unicase = "2.6"
unplug = { path = "../unplug" }

[dev-dependencies]
unplug-test = { path = "../unplug-test" }