[package]
name = "unplug-test"
version = "0.2.0"
authors = ["Derpky"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = { version = "0.4", features = ["release_max_level_debug"] }
simplelog = "0.10"
tempfile = "3"
unplug = { path = "../unplug" }

[dev-dependencies]
lazy_static = "1.4.0"
serial_test = "*"