name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: windows-x64
          os: windows-latest
          target: x86_64-pc-windows-msvc
          exe-name: unplug.exe
        - name: macos-arm64
          os: macos-latest
          target: aarch64-apple-darwin
          exe-name: unplug
        - name: macos-x64
          os: macos-latest
          target: x86_64-apple-darwin
          exe-name: unplug
        - name: linux-x64
          os: ubuntu-latest
          target: x86_64-unknown-linux-musl
          exe-name: unplug
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - if: ${{ contains(matrix.os, 'ubuntu') }}
      name: Install Dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev
    - name: Install Toolchain
      run: |
        rustup default 1.56
        rustup target add ${{ matrix.target }}
    - if: ${{ contains(matrix.target, 'x86_64') }}
      name: Build Tests (x64)
      run: cargo test -v --workspace --no-run --target ${{ matrix.target }}
    - if: ${{ contains(matrix.target, 'x86_64') }}
      name: Run Tests (x64)
      run: cargo test -v --workspace --lib --target ${{ matrix.target }}
    - name: Build CLI
      run: cargo build -v -p unplug-cli --target ${{ matrix.target }} --release --no-default-features --features distribution
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
       name: unplug-${{ github.ref_name }}-${{ matrix.name }}
       path:
         target/release/${{ matrix.exe-name }}
       if-no-files-found: error
